{{- if and (not .Values.existingSecret) .Values.rsaPrivateKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grantex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grantex.labels" . | nindent 4 }}
type: Opaque
data:
  RSA_PRIVATE_KEY: {{ .Values.rsaPrivateKey | b64enc }}
{{- end }}
